# Generated by Django 4.2.16 on 2024-10-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('verdura', 'Verdura'), ('fruta', 'Fruta')], max_length=15)),
                ('precio', models.PositiveBigIntegerField()),
                ('fecha_caducidad', models.DateField()),
                ('tipo_cantidad', models.CharField(choices=[('kilo', 'Kilo'), ('saco', 'Saco'), ('cajon', 'Cajón'), ('malla', 'Mall')], max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
