# Generated by Django 4.2.16 on 2024-10-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tipo_cantidad',
            field=models.CharField(choices=[('kilo', 'Kilos'), ('saco', 'Sacos'), ('cajon', 'Cajones'), ('malla', 'Mallas')], max_length=15),
        ),
    ]
