# Generated by Django 4.2.16 on 2024-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_productos_tipo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tipo_cantidad',
            field=models.CharField(choices=[('unt.', 'Unitario'), ('kilo', 'Kilos'), ('saco', 'Sacos'), ('cajon', 'Cajones'), ('malla', 'Mallas')], max_length=15),
        ),
    ]
