# Generated by Django 4.2.16 on 2024-11-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_productos_tipo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('nombreProducto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('verdura', 'Verdura'), ('fruta', 'Fruta')], max_length=15)),
                ('tipo_cantidad', models.CharField(choices=[('unt.', 'Unidades'), ('kilo', 'Kilos'), ('saco', 'Sacos'), ('cajon', 'Cajones'), ('malla', 'Mallas')], max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
                ('Total', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('Telefono_gmail', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='slug',
            field=models.SlugField(default='producto', max_length=200, unique=True),
        ),
    ]
