# Generated by Django 4.2.16 on 2024-11-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_compras_proveedores_productos_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='slug',
        ),
    ]
