# Generated by Django 4.2.16 on 2024-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_productos_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='nombreProducto',
        ),
        migrations.AddField(
            model_name='compras',
            name='producto_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
