# Generated by Django 4.2.16 on 2024-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_compras_nombreproducto_compras_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='compras',
            name='nombreProducto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
