# Generated by Django 4.2.16 on 2024-11-14 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_compras_producto_id_compras_nombreproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='nombreProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='tienda.productos'),
        ),
    ]
