# Generated by Django 4.2.16 on 2024-11-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_compras_nombreproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_cantidad', models.CharField(choices=[('unt.', 'Unidades'), ('kilo', 'Kilos'), ('saco', 'Sacos'), ('cajon', 'Cajones'), ('malla', 'Mallas')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.productos')),
            ],
        ),
    ]
