# Generated by Django 4.2.16 on 2024-11-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_productocompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocompra',
            name='precio',
        ),
    ]
