# Generated by Django 4.2.16 on 2024-11-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_remove_productocompra_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='tipo_cantidad',
        ),
        migrations.AddField(
            model_name='productocompra',
            name='tipo',
            field=models.CharField(choices=[('verdura', 'Verdura'), ('fruta', 'Fruta')], default=0, max_length=15),
            preserve_default=False,
        ),
    ]
