# Generated by Django 4.2.16 on 2024-11-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_compras_cantidad_remove_compras_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocompra',
            name='tipo',
        ),
    ]
