# Generated by Django 4.2.16 on 2024-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_clientes_ventas_productoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cantidad_compras',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
