# Generated by Django 4.2.16 on 2024-11-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_alter_productoventa_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocompra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.productos'),
        ),
    ]
