# Generated by Django 4.2.16 on 2024-11-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_alter_productocompra_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='fecha_caducidad',
        ),
    ]
