# Generated by Django 4.2.16 on 2024-11-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_remove_productos_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
