# Generated by Django 4.2.16 on 2024-12-02 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_alter_productos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')]),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='rut_cliente',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')]),
        ),
    ]
